### ISSUE TITLE
loaders unnecessary

### ISSUE THREAD

**Issue by jasonmacdonald** [aprasadh/lds-marko#1]
Just a heads up, your Webpack.config is already set to load styles from requires, so the `!style-loader!css-loader!@` in client.js shouldn't be necessary. Webpack will already pick-up and process the stylesheet. :) You can just require the stylesheet directly.

**Comment by aprasadh** [comment]
Somehow the webpack.config.js settings were not picking up. I have to override through client.js. Let me work on it again. Thanks for my first ticket.

**Comment by aprasadh** [comment]
Updated `client.js` file by removing unnecessary loader statements.
